---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    private_network:
      type: dhcp

provisioner:
  name: chef_zero
  #require_chef_omnibus: 12.19.36

platforms:
  - name: debian-7.7
  - name: ubuntu-14.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
      apt:
        compile_time_update: true
        confd:
          install_recommends: false
